// src/components/Header.tsx
import React, { useState } from 'react';
import RprMasterLogo from './brand/RprMasterLogo';
import { useAuth } from '../contexts/AuthContext';
import { Link } from 'react-router-dom';
import { GoogleIcon } from './icons/GoogleIcon';

/**
 * TS-Λ3 // HARBOR A HEADER [v5.0.0]
 * PATTERN: KONTROL + Google Sign In (Side-by-Side)
 * SOVEREIGN NAVIGATION: METHODS, LABS, OVERWATCH
 */
export const Header: React.FC = () => {
  const { user, signIn } = useAuth();
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const navLinks = [
    { name: 'FOUNDATIONS', href: '/#foundations' },
    { name: 'METHODS', href: '/#methods' },
    { name: 'PROCESS', href: '/#process' },
    { name: 'OVERWATCH', href: '/#overwatch' },
  ];

  return (
    <header className="fixed top-0 w-full z-[100] bg-black/80 backdrop-blur-md border-b border-white/10 h-[108px]">
      <div className="max-w-7xl mx-auto h-full w-full flex items-center justify-between px-4 md:px-12 relative z-10">

        {/* Left: Branding Lockup */}
        <div className="flex items-center gap-4 py-2">
          <Link to="/">
            <RprMasterLogo />
          </Link>
        </div>

        {/* Center: Primary Navigation (Desktop Only) */}
        <nav className="hidden lg:flex items-center gap-8 text-[10px] font-black tracking-[0.2em] uppercase text-zinc-500">
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              className="hover:text-white transition-colors"
            >
              {link.name}
            </a>
          ))}
        </nav>

        {/* Right: Dual CTA Latch + Mobile Toggle */}
        <div className="flex items-center gap-x-3 md:gap-4">

          {/* Primary Action: KONTROL [G] */}
          <a
            href="https://kontrol.rprcomms.com"
            className="flex items-center gap-2 md:gap-3 bg-zinc-900 border border-white/10 hover:border-cyan-500/50 px-3 md:px-5 py-2 md:py-2.5 rounded transition-all group shadow-xl"
          >
            <div className="w-1.5 md:w-2 h-1.5 md:h-2 bg-cyan-500 rounded-full animate-pulse shadow-[0_0_10px_#00E0FF]" />
            <span className="text-[9px] md:text-[10px] font-black uppercase tracking-[0.15em] md:tracking-[0.2em] text-white">
              KONTROL [G]
            </span>
          </a>

          {/* Secondary Action: Identity Latch with Google Icon */}
          {user ? (
            <div className="w-10 h-10 rounded-full border border-cyan-500/50 overflow-hidden shadow-[0_0_15px_rgba(0,224,255,0.3)]">
              <img
                src={user.photoURL || ''}
                alt={user.displayName || 'User'}
                className="w-full h-full object-cover"
              />
            </div>
          ) : (
            <button
              onClick={signIn}
              className="flex-shrink-0 transition-all hover:border-cyan-500/50 hover:shadow-[0_0_15px_rgba(0,224,255,0.3)]"
              aria-label="Sign in with Google"
            >
              <GoogleIcon size={40} />
            </button>
          )}

          {/* Mobile Menu Toggle */}
          <button
            className="lg:hidden w-10 h-10 flex items-center justify-center text-zinc-500 hover:text-white"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            <span className="material-symbols-outlined">{isMenuOpen ? 'close' : 'menu'}</span>
          </button>
        </div>
      </div>

      {/* Mobile Menu Overlay */}
      {isMenuOpen && (
        <div className="lg:hidden fixed inset-0 top-[108px] bg-black z-50 p-6 flex flex-col gap-8 animate-in fade-in slide-in-from-top-4">
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              className="text-2xl font-black tracking-widest text-zinc-500 hover:text-cyan-500 uppercase transition-colors"
              onClick={() => setIsMenuOpen(false)}
            >
              {link.name}
            </a>
          ))}
          <a
            href="https://kontrol.rprcomms.com"
            className="text-2xl font-black tracking-widest text-cyan-500 hover:text-cyan-400 uppercase transition-colors"
            onClick={() => setIsMenuOpen(false)}
          >
            KONTROL [G]
          </a>
        </div>
      )}
    </header>
  );
};

// RPR-LEGACY-ARCHIVE/angular-mothership/RPR-WEBSITE/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * RPR MOTHERSHIP | HEADER COMPONENT [v4.0.1]
 * Role: Architect Layer (Strategic Logic)
 * Constraints: 108px Fixed Height, Zero CLS.
 * Update: Liquidated NG5002 (@ escape) and unused import warning.
 */
@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  template: `
    <header class="h-[108px] fixed top-0 w-full z-[100] bg-black/80 backdrop-blur-md border-b border-white/5 flex items-center px-[20px] md:px-12 overflow-hidden">
      
      <!-- ARCHITECT SUBSTRATE: STRATEGIC CHESS GRID -->
      <div class="absolute inset-0 z-0 opacity-[0.08] pointer-events-none">
        <div class="grid grid-cols-8 grid-rows-2 h-full w-full">
          <div *ngFor="let i of [].constructor(16); let idx = index" 
               class="border-[0.5px] border-primary/10 grid-square-anim"
               [style.animation-delay.s]="idx * 0.7">
          </div>
        </div>
      </div>

      <div class="max-w-7xl mx-auto w-full flex justify-between items-center relative z-10">
        
        <!-- LEFT: BRAND LATCH -->
        <div class="flex items-center gap-4 py-2">
          <div class="relative group h-10 w-10 flex items-center justify-center">
            <div class="absolute inset-0 bg-primary/20 blur-lg group-hover:bg-primary/40 transition-all duration-700"></div>
            <span class="material-symbols-outlined text-primary text-3xl relative z-10">radar</span>
          </div>
          <div class="flex flex-col leading-none">
            <span class="font-black text-xl tracking-tighter uppercase text-white">RPR</span>
            <span class="text-[9px] font-bold text-primary tracking-[0.3em] uppercase mt-1">Communications</span>
          </div>
        </div>

        <!-- CENTER: STRATEGIC NAV -->
        <nav class="hidden md:flex items-center gap-10 text-[10px] font-bold tracking-[0.2em] uppercase text-slate-400">
          <a class="hover:text-primary transition-colors" href="#foundations">Methods</a>
          <a class="hover:text-primary transition-colors" href="/products">Products</a>
          <a class="hover:text-primary transition-colors" href="#overwatch">Overwatch</a>
        </nav>

        <!-- RIGHT: KONTROL LATCH -->
        <div class="flex items-center gap-6">
          <div class="hidden lg:flex flex-col items-end border-r border-white/10 pr-6">
            <span class="text-[9px] font-black text-white/20 uppercase tracking-widest leading-none mb-1">Auth Principal</span>
            <span class="text-[11px] font-mono text-primary leading-none uppercase">hello&#64;butterdime.com</span>
          </div>

          <a href="https://kontrol.rprcomms.com" 
             class="flex items-center gap-3 bg-zinc-900 border border-white/10 hover:border-primary/50 px-4 py-2.5 rounded-lg transition-all group shadow-sm">
            <span class="flex h-5 w-5 items-center justify-center rounded-sm bg-white overflow-hidden">
              <img src="https://www.google.com/favicon.ico" alt="G" class="h-3 w-3" />
            </span>
            <span class="text-[10px] font-black uppercase tracking-[0.2em] group-hover:text-primary transition-colors text-white whitespace-nowrap">
              KONTROL LATCH
            </span>
          </a>
        </div>

      </div>
    </header>
  `,
  styles: [`
    @keyframes architectScan {
      0%, 100% { background: transparent; opacity: 0.1; }
      5% { background: rgba(0, 224, 255, 0.4); box-shadow: inset 0 0 15px #00E0FF; opacity: 1; }
      10% { background: transparent; opacity: 0.1; }
    }
    .grid-square-anim {
      animation: architectScan 10s infinite ease-in-out;
    }
    :host { display: block; }
  `]
})
export class HeaderComponent {}
